# Generated by Django 5.2 on 2025-10-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_db',
            fields=[
                ('Car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=10)),
                ('Model_car', models.CharField(max_length=10)),
                ('Purchase_date', models.DateField()),
                ('Mileage', models.FloatField()),
            ],
        ),
    ]
